#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
#
# Build the controlled-v1 stack with a declared local signing repository.
# The wrapper is deliberately fail-closed: it never permits Kbuild's default
# autogenerated signing key to establish a release contract.

set -euo pipefail

readonly V1_CERT_DER_SHA256=04093d5e0b816927dc1e4fcdbd4ec754df6e69960918aa2eaa69bea6878f6faf
readonly STOCK_CERT_DER_SHA256=f28dbcc60085b21a3cff1342482897fa640b468847473147834f26c4feb2df43
readonly TRUSTED_BUNDLE_SHA256=c1c17586a8bbd564a39b297d39a267b02ab4a266c0deaf81d536d026e68188a7

die() {
    printf 'error: %s\n' "$*" >&2
    exit 2
}

usage() {
    cat <<'EOF'
Usage:
  tools/build-controlled-oos-signing-v1.sh [--clean] [--all] \
      [--signing-repo <path>] [--expect-source-id <commit>]

The signing repository defaults to:
  ~/.config/oneplus15-kernel/signing-v1

--all additionally runs the strict ABI, KMI symbol-check, and ABI-diff targets.
EOF
}

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
signing_repo="${HOME}/.config/oneplus15-kernel/signing-v1"
expect_source_id=
do_clean=0
do_all=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --signing-repo)
            signing_repo=${2:-}
            [[ -n "$signing_repo" ]] || die "--signing-repo requires a path"
            shift 2
            ;;
        --expect-source-id)
            expect_source_id=${2:-}
            [[ -n "$expect_source_id" ]] || die "--expect-source-id requires a commit"
            shift 2
            ;;
        --clean)
            do_clean=1
            shift
            ;;
        --all)
            do_all=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            usage >&2
            die "unknown argument: $1"
            ;;
    esac
done

signing_repo=$(cd "$signing_repo" && pwd) || die "missing signing repository: $signing_repo"
key="$signing_repo/module-signing-v1.pem"
cert_der="$signing_repo/module-signing-v1.x509"
cert_pem="$signing_repo/module-signing-v1-cert.pem"
for path in "$key" "$cert_der" "$cert_pem" "$signing_repo/BUILD.bazel" "$signing_repo/MODULE.bazel"; do
    [[ -f "$path" ]] || die "controlled-v1 signing repository is incomplete: $path"
done
[[ $(stat -c '%a' "$key") == 600 ]] || die "controlled-v1 private key must be mode 600"

cert_sha=$(sha256sum "$cert_der" | awk '{print $1}')
[[ "$cert_sha" == "$V1_CERT_DER_SHA256" ]] || die "unexpected controlled-v1 signing certificate"
key_public=$(openssl pkey -in "$key" -pubout 2>/dev/null | openssl pkey -pubin -outform DER 2>/dev/null | sha256sum | awk '{print $1}') ||
    die "unable to read controlled-v1 private key"
cert_public=$(openssl x509 -in "$cert_pem" -pubkey -noout 2>/dev/null | openssl pkey -pubin -outform DER 2>/dev/null | sha256sum | awk '{print $1}') ||
    die "unable to read controlled-v1 public certificate"
[[ "$key_public" == "$cert_public" ]] || die "controlled-v1 private key does not match public certificate"

tracked_cert="$repo_root/kernel_platform/common/certs/controlled_oos_signing_v1.pem"
stock_cert="$repo_root/kernel_platform/common/certs/oos16_0_9_400_stock_gki_module_signing.pem"
trusted_bundle="$repo_root/kernel_platform/common/certs/controlled_oos_signing_v1_trusted.pem"
[[ $(openssl x509 -in "$tracked_cert" -outform DER | sha256sum | awk '{print $1}') == "$V1_CERT_DER_SHA256" ]] ||
    die "tracked controlled-v1 certificate differs from the signing repository"
[[ $(openssl x509 -in "$stock_cert" -outform DER | sha256sum | awk '{print $1}') == "$STOCK_CERT_DER_SHA256" ]] ||
    die "tracked stock OOS certificate differs from the reviewed trust contract"
[[ $(sha256sum "$trusted_bundle" | awk '{print $1}') == "$TRUSTED_BUNDLE_SHA256" ]] ||
    die "controlled-v1 trusted bundle differs from the reviewed trust contract"
[[ $(openssl crl2pkcs7 -nocrl -certfile "$trusted_bundle" | openssl pkcs7 -print_certs -noout | grep -c '^subject=') == 2 ]] ||
    die "controlled-v1 trusted bundle must contain exactly stock and v1 certificates"

status_file="$repo_root/kernel_platform/common/workspace_status.json"
cleanup() {
    [[ ! -e "$status_file" && ! -L "$status_file" ]] || rm -f -- "$status_file"
}
trap cleanup EXIT HUP INT TERM

source_args=(--write-workspace-status "$status_file")
[[ -z "$expect_source_id" ]] || source_args+=(--expect-source-id "$expect_source_id")
source_id=$("$repo_root/tools/compute-controlled-oos-source-id.sh" "${source_args[@]}")

bazel_args=(--override_module="oneplus15_signing=$signing_repo")
cd "$repo_root/kernel_platform"
if ((do_clean)); then
    tools/bazel clean
fi
tools/bazel build "${bazel_args[@]}" //soc-repo:canoe_perf_dist
if ((do_all)); then
    tools/bazel build "${bazel_args[@]}" \
        //common:kernel_aarch64_abi \
        //common:kernel_aarch64_abi_kmi_symbol_checks \
        //common:kernel_aarch64_abi_diff
fi

kernel_build_dir="$repo_root/kernel_platform/bazel-bin/common/kernel_aarch64"
config="$kernel_build_dir/.config"
release_file="$kernel_build_dir/include/config/kernel.release"
signing_x509="$kernel_build_dir/certs/signing_key.x509"
vmlinux="$kernel_build_dir/vmlinux"
for path in "$config" "$release_file" "$signing_x509" "$vmlinux"; do
    [[ -f "$path" ]] || die "Kleaf did not produce required controlled-v1 output: $path"
done

source_short=$(git -C "$repo_root" rev-parse --short=12 "$source_id")
kernel_release=$(<"$release_file")
[[ "$kernel_release" == *"-g${source_short}-4k" ]] ||
    die "kernel release does not contain the derived controlled-v1 source identity: $kernel_release"

for setting in \
    'CONFIG_MODULE_SIG=y' \
    'CONFIG_MODULE_SIG_PROTECT=y' \
    'CONFIG_MODVERSIONS=y' \
    'CONFIG_GENDWARFKSYMS=y' \
    'CONFIG_MODULE_SIG_KEY="module-signing-v1.pem"' \
    'CONFIG_SYSTEM_TRUSTED_KEYS="controlled_oos_signing_v1_trusted.pem"'; do
    grep -qx "$setting" "$config" || die "controlled-v1 config guard failed: $setting"
done

[[ $(sha256sum "$signing_x509" | awk '{print $1}') == "$V1_CERT_DER_SHA256" ]] ||
    die "Kbuild substituted an unexpected module-signing certificate"
python3 "$repo_root/tools/verify-controlled-oos-signing-v1.py" \
    --vmlinux "$vmlinux" \
    --signing-x509 "$signing_x509" \
    --project-cert "$tracked_cert" \
    --stock-cert "$stock_cert"

printf 'CONTROLLED-V1 BUILD PASS\n'
printf 'kernel_source_id=%s\n' "$source_id"
printf 'kernel_release=%s\n' "$kernel_release"
printf 'module_signing_certificate_sha256=%s\n' "$V1_CERT_DER_SHA256"
printf 'trusted_bundle_sha256=%s\n' "$TRUSTED_BUNDLE_SHA256"
